# Research findings. verdict: ADD | MERGE | EXCLUDE | VERIFY
# confidence: verified (web-searched this session) | inferred (not searched)
NEEDS_REVIEW = {
 'BASF': dict(verdict='ADD', zip='48192', bucket='Core 12',
   category='Advanced Manufacturing & Heavy Industry', sub='Chemicals & Plastics',
   web='https://www.basf.com/us/en/careers', conf='verified',
   note='Wyandotte site, 1609 Biddle Ave. Purchased 1969, 5 production facilities + R&D. Actively hiring plant operators/technicians. Anchor corridor employer.'),
 'Hacienda Foods (Hacienda Mexican Foods)': dict(verdict='ADD', zip='48210', bucket='Core 12',
   category='Advanced Manufacturing & Heavy Industry', sub='Food Production',
   web='https://www.facebook.com/HaciendaMexicanFoods/', conf='verified',
   note='Latina-owned, family-run tortilla manufacturer in Mexicantown since 1994. Hiring Lead Maintenance $30-40/hr. No careers page; FB + phone 313-895-8823 are the real apply routes.'),
 'C100 Quaker Houghton US OPS': dict(verdict='ADD', zip='48238', bucket='Detroit (other)',
   category='Advanced Manufacturing & Heavy Industry', sub='Chemicals & Plastics',
   web='https://careers.quakerhoughton.com/jobs/michigan', conf='verified',
   note='Industrial process fluids. 6 Detroit openings incl. Line Operator, Facilities Maintenance Tech. Rename to "Quaker Houghton - Detroit"; C100 is an internal site code.'),
 'Perigee Manufacturing Company': dict(verdict='ADD', zip='48238', bucket='Detroit (other)',
   category='Advanced Manufacturing & Heavy Industry', sub='Metal Fabrication',
   web='https://perigeemfg.com/', conf='verified',
   note='Screw-machined/CNC fasteners, founded 1965, 11-50 employees. NOTE: master lists 10 open jobs, implausible at this headcount - re-check the job match.'),
 'ABM Industries': dict(verdict='VERIFY', zip='48226', bucket='Detroit (other)',
   category='Commercial, Hospitality & Retail', sub='Facilities Services',
   web='https://www.abm.com/careers/', conf='inferred',
   note='48226 is a downtown office address, not a worksite. National facilities contractor - its jobs are dispersed across client sites. Mapping the office may mislead.'),
 'Bakelite': dict(verdict='EXCLUDE', zip='48390', bucket='Outside corridor',
   category='', sub='', web='', conf='verified',
   note='Commerce Township, ~35 mi from the corridor. Outside the 12 ZIPs.'),
 'Continuum Services': dict(verdict='EXCLUDE', zip='48335', bucket='Outside corridor',
   category='', sub='', web='', conf='verified',
   note='Farmington Hills HQ. Facilities contractor, same dispersed-worksite problem as ABM.'),
 'Dinsmore & Shohl LLP': dict(verdict='EXCLUDE', zip='48084', bucket='Outside corridor',
   category='', sub='', web='', conf='verified',
   note='Troy law firm. Neither in corridor nor an industrial/port employer. Clear drop.'),
}

CANDIDATES = {
 'Dorsey College': dict(verdict='ADD', loc='Woodhaven, MI', zip='48183', bucket='Core 12',
   category='Education & Workforce Development', sub='Career & Technical Training',
   web='https://lindenwood.wd1.myworkdayjobs.com/Dorsey_College_External_Careers', conf='verified',
   note='Woodhaven campus explicitly serves Downriver: Southgate, Taylor, Wyandotte, Lincoln Park, Allen Park. Trains medical assistants, HVAC techs, practical nurses, EMTs. Strong fit - it is a workforce pipeline, not just an employer.'),
 'McInnis Cement': dict(verdict='MERGE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='verified',
   note='Merged with Votorantim Cimentos in 2020; VCNA is ALREADY on the map. Same operation under an old name. Merge these 2 jobs into the existing VCNA record - do not add a second pin.'),
 'sensus': dict(verdict='ADD', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Advanced Manufacturing & Heavy Industry', sub='Industrial Equipment',
   web='https://www.xylem.com/en-us/support/find-a-location/detroit-mi/', conf='verified',
   note='Real employer, wrong name. Sensus is a Xylem brand; the Detroit pump-repair jobs are Godwin/Xylem at its Detroit rental location. Add as "Xylem (Godwin) - Detroit" and confirm street address.'),
 'Roper Thermals': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='verified',
   note='Company is in Clinton, CONNECTICUT - the only US site. Scraper location field is simply wrong. Evidence the location column cannot be trusted alone.'),
 'Rockville Loop': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='verified',
   note='Recruiting shell posting Amazon dock jobs across Battle Creek, Wilmington and elsewhere via Lensa/BeBee. Intermediary my keyword filter missed.'),
 'Coastal Elite Pro': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='verified',
   note='Same CDL owner-operator ad reposted in Topeka, Toledo, Bloomington, Minneapolis, St Cloud. Driver-recruiting shell, no Detroit facility.'),
 'Packaging Corporation of America': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='verified',
   note='PCA has no Detroit plant. Michigan sites are Grand Rapids, Grandville, Edmore, Filer City - all 100+ mi away. Location field wrong again.'),
 'DMC Sinai-Grace Hospital': dict(verdict='ADD', loc='Detroit, MI', zip='48235', bucket='Detroit (other)',
   category='Healthcare & Public Safety', sub='Hospitals',
   web='https://www.dmc.org/careers', conf='inferred', note='Major Detroit hospital, real worksite. Confirm ZIP before adding.'),
 'Detroit Medical Center': dict(verdict='ADD', loc='Detroit, MI', zip='48201', bucket='Detroit (other)',
   category='Healthcare & Public Safety', sub='Hospitals',
   web='https://www.dmc.org/careers', conf='inferred', note='DMC main campus. Note overlap with the 3 other DMC-family entries - decide one pin or several.'),
 'Detroit Medical Center Shared Services': dict(verdict='MERGE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Administrative arm of DMC, not a separate worksite. Fold into Detroit Medical Center.'),
 'Conifer Health Solutions': dict(verdict='MERGE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Tenet revenue-cycle arm; postings are Harper Hutzel patient-access roles. Fold into the DMC/Tenet hospital record.'),
 'Tenet Regional Resource Pool': dict(verdict='MERGE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Tenet float pool, not a site. Postings say "TRA Detroit Med Ctr". Fold into DMC.'),
 'DMC Huron Valley-Sinai Hospital': dict(verdict='EXCLUDE', loc='(none)', zip='48393', bucket='Outside corridor',
   category='', sub='', web='', conf='inferred', note='Commerce Township, far outside corridor despite the DMC name.'),
 'Amentum': dict(verdict='VERIFY', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Advanced Manufacturing & Heavy Industry', sub='Engineering & Testing',
   web='https://www.amentum.com/careers/', conf='inferred', note='Emissions/fluid-analysis lab roles suggest a real Detroit-area technical site, possibly at a client facility. Worth one lookup.'),
 'Syncreon': dict(verdict='VERIFY', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Transportation, Logistics & Distribution', sub='Third-Party Logistics',
   web='https://www.dpworld.com/careers', conf='inferred', note='Auto-sector 3PL, acquired by DP World. Historically Auburn Hills HQ - confirm whether a corridor warehouse exists.'),
 'HTC Global Services': dict(verdict='EXCLUDE', loc='Dearborn, MI', zip='48126', bucket='Detroit (other)',
   category='', sub='', web='', conf='inferred', note='IT services, Troy-headquartered. Support roles, not port/industrial work.'),
 'POWER ELECTRONICS': dict(verdict='VERIFY', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Energy, Utilities & Environmental Services', sub='Clean Energy',
   web='', conf='inferred', note='EV-charger electrician roles. Relevant to the hydrogen/clean-energy layer if the site is real - worth checking for that reason alone.'),
 'Impact Label Corporation': dict(verdict='VERIFY', loc='(none)', zip='', bucket='VERIFY ZIP',
   category='Advanced Manufacturing & Heavy Industry', sub='Printing & Packaging',
   web='', conf='inferred', note='Only a "General Inquiry" posting and no location. Low value.'),
 'Trajectory Energy': dict(verdict='EXCLUDE', loc='(none)', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Posting is explicitly Remote. No physical corridor worksite.'),
 'Allied Universal': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Contract security. Guards are posted to client sites; no mappable workplace of its own.'),
 'Compass Group': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Food-service contractor; one posting is Eastern Michigan University in Ypsilanti. Dispersed client sites.'),
 'Delaware North': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Comerica Park concessions. Stadium hospitality, outside the corridor and outside the industrial remit.'),
 'Deloitte': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Professional services downtown. Not port/industrial; roles need degrees the map is not targeting.'),
 'KFC Careers': dict(verdict='EXCLUDE', loc='Taylor, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Franchise fast food. "KFC Careers" is a posting account, not an employer entity.'),
 'Meijer': dict(verdict='VERIFY', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Commercial, Hospitality & Retail', sub='Grocery & Retail',
   web='https://jobs.meijer.com/', conf='inferred', note='Real fixed store sites and genuinely accessible entry-level work. Add only if a corridor store exists.'),
 'The Home Depot': dict(verdict='VERIFY', loc='Detroit, MI', zip='', bucket='VERIFY ZIP',
   category='Commercial, Hospitality & Retail', sub='Grocery & Retail',
   web='https://careers.homedepot.com/', conf='inferred', note='Same reasoning as Meijer - fixed site, accessible roles. Confirm which store.'),
 'Tata Technologies': dict(verdict='EXCLUDE', loc='Detroit, MI', zip='', bucket='-',
   category='', sub='', web='', conf='inferred', note='Engineering consultancy, Novi-based. Senior mechanical engineer roles; not corridor, not accessible-entry work.'),
}
